### ISSUE TITLE
Set space name in product.json

### ISSUE THREAD

**Issue by soichih** [giulia-berto/app-ants-mni#1]
I've been working to standardize how we set "Space" for various datatypes in brainlife. Can you update this App so that it will generate the following content in product.json?

```
{
    "track_aligned": {
        "meta": {
            "Space": "MNI152Lin"
        },
        "tag": [
            "space-MNI152Lin"
        ]
    }
}
```

The name `MNI152Lin` comes from BIDS specification
> https://bids-specification.readthedocs.io/en/stable/99-appendices/08-coordinate-systems.html#template-based-coordinate-systems

I am not 100% sure MNI152Lin is the most appropriate space name for the output from this App, however. Please choose the most appropriate space name listed in the BIDS spec.

**Comment by soichih** [comment]
FYI.. you can just create product.json with the content above and store it in the git repo .. so that it will be *generated* as soon as the App starts (you don't have to write it out from your App)

**Comment by giulia-berto** [comment]
Done. Can you please add other resources?
